### ISSUE TITLE
Problems with 16.0.3

### ISSUE THREAD

**Issue by daniellemccool** [cjvanlissa/TCSM#6]
From Noémi:

16.0.3 CFI is acceptable, RMSEA is not.   The results show that the RMSEA confidence interval contains 0.05 so not sure this is a completely fair conclusion

**Comment by cjvanlissa** [comment]
@daniellemccool the point estimate is .103, that well exceeds .08... I've never seen anyone argue that, as long as the confidence interval includes acceptable values, the fit is acceptable - instead, I've always thought that the upper bound of the interval should fall below the threshold of .08?

**Comment by daniellemccool** [comment]
I'm not well-informed enough myself to have an opinion here.

http://davidakenny.net/cm/fit.htm#:~:text=A%20confidence%20interval%20can%20be,08.

> A confidence interval can be computed for the RMSEA. Ideally the lower value of the 90% confidence interval includes or is very near zero (or no worse than 0.05) and the upper value is not very large, i.e., less than .08.   The width of the confidence interval is very informative about the precision in the estimate of the RMSEA.

**Comment by cjvanlissa** [comment]
I think this reference is in line with my interpretation..
